version: '3'
services:
    nginx:
        depends_on:
            - 'api'
            - 'client'
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3000:80'
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./transport-api
        volumes: 
            - /app/node_modules
            - ./transport-api:/app
        environment:
            - PORT=5000
        expose:
            - '5000'
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./transport-client
        volumes:
            - /app/node_modules
            - ./transport-client:/app
        expose:
            - '3000'
        stdin_open: true